version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    restart: unless-stopped
